# -*- coding: utf-8 -*-
"""HuggingFaceDeployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cacoUwhf8ATkPwfg8xHkfn24z-u7yN38
"""

import os
os.chdir('/content/')

!pip install huggingface_hub

!huggingface-cli login

!huggingface-cli repo create DialoGPT-small-TChalla

!sudo apt-get install git-lfs

"""This allows for a push of models and lfs means large files storage

> Indented block

to reacquire the token just use
!cat /root/.huggingface/token
"""

!git clone https://CodeMaestro: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@huggingface.co/CodeMaestro/DialoGPT-small-TChalla

!ls

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/output-small/"

#now during the training of the model for the attributes we stored the model in a dir called output-small
!mv /content/drive/My\ Drive/output-small/* DialoGPT-small-TChalla/

os.chdir("DialoGPT-small-TChalla")

"""the change to the DialoGPT-small-TChalla dir is cz after we move the content of the trained mdoel there we are going to push from there"""

!git lfs install

!ls

!pwd

!git status

!git add .

#adding my credentials so that I never have to do this again and this are hugging face credentials
!git config --global user.email "francismurithi475@gmail.com"
!git config --global user.name "CodeMaestro"

!git commit -m "Initial Commit"

!git push

